### ISSUE TITLE
Не работает.

### ISSUE THREAD

**Issue by AnPogrebnyak** [MarharytaTsepiennikova/homework_4#3]
1, 2, 3, 4 ->4, 3, 3, 1
Куда делась двойка?
https://github.com/MarharytaTsepiennikova/homework_4/blob/da230297311b16a5c24f98f3f80009f6948bc917/src/Homework4_9.java#L8

**Comment by MarharytaTsepiennikova** [comment]
переделала https://github.com/MarharytaTsepiennikova/homework_4/blob/master/src/Homework4_9.java
